   
lowercaseOutputName: true
rules:
- pattern : kafka.server:name=(.+),topic=(.+),type=(.+)<>OneMinuteRate,Count,MeanRate
  name: kafka_server_$3_$1
  labels:
    topic: "$2"
- pattern : kafka.cluster:name=(.+),partition=(.+),topic=(.+),type=(.+)<>Value
  name: kafka_cluster_$4_$1
  labels:
    topic: "$3"
    partition: "$2"
- pattern : kafka.log:name=(.+), partition=(.+), topic=(.+), type=Log<>Value
  name: kafka_log_$1
  labels:
    topic: "$3"
    partition: "$2"
- pattern : kafka.controller:name=(.+), type=(.+)<>Count,Value
  name: kafka_controller_$2_$1
- pattern : kafka.network:name=(.+), type=(.+)<>Count,Value
  name: kafka_network_$2_$1
- pattern : kafka.network:name=(.+)PerSec, request=(.+), type=(.+)<>Count
  name: kafka_network_$3_$1_total
  labels:
    request: "$2"
- pattern : kafka.network:name=(\w+), networkProcessor=(.+), type=(.+)<>Count,Value
  name: kafka_network_$3_$1
  labels:
    request: "$2"
  type: COUNTER
- pattern : kafka.network:name=(\w+), request=(\w+), type=(.+)<>Count
  name: kafka_network_$3_$1
  labels:
    request: "$2"
- pattern : kafka.server:name=(\w+)PerSec\w*, topic=(.+), type=(.+)<>Count,OneMinuteRate,MeanRate
  name: kafka_server_$3_$1_total
  labels:
    topic: "$2"
- pattern : kafka.server:name=(.+)PerSec\w*, type=(.+)<>Count
  name: kafka_server_$2_$1_total
  type: COUNTER
- pattern : kafka.server:clientId=(.+), name=(.+), partition=(.*), topic=(.+), type=(.+)<>Count,Value
  name: kafka_server_$5_$2
  labels:
    clientId: "$1"
    topic: "$4"
    partition: "$3"
- pattern : kafka.cluster:name=(.+), partition=(.*), topic=(.+), type=(.+)<>Count,Value
  name: kafka_server_$4_$1
  labels:
    topic: "$3"
    partition: "$2"
- pattern : kafka.server:name=(.+), topic=(.+), type=(.+)<>Count,Value
  name: kafka_server_$3_$1
  labels:
    topic: "$2"
  type: COUNTER
- pattern : kafka.server:brokerHost=(.+), brokerPort=(.+), clientId=(.+), name=(.+), type=(.+)<>Count,Value
  name: kafka_server_$5_$4
  labels:
    clientId: "$3"
    broker: "$1:$2"
- pattern : kafka.server:clientId=(.+), name=(.+), type=(.+)<>Count,Value
  name: kafka_server_$3_$2
  labels:
    clientId: "$1"
- pattern : kafka.server:name=(.+), type=(.+)<>Count,Value
  name: kafka_server_$2_$1
- pattern : kafka.(\w+):name=(.+)PerSec\w*, type=(.+)<>Count
  name: kafka_$1_$3_$2_total
- pattern : kafka.(\w+):name=(.+)PerSec\w*, topic=(.+), type=(.+)<>Count
  name: kafka_$1_$4_$2_total
  labels:
    topic: "$3"
  type: COUNTER
- pattern : kafka.(\w+):name=(.+)PerSec\w*, partition=(.+), topic=(.+), type=(.+)<>Count
  name: kafka_$1_$5_$2_total
  labels:
    topic: "$4"
    partition: "$3"
  type: COUNTER
- pattern : kafka.(\w+):name=(\w+), type=(.+)<>Count,Value,MeanRate
  name: kafka_$1_$3_$2
  type: COUNTER

#- pattern : kafka.(\w+)<type=(.+), name=(.+), (\w+)=(.+)><>(Count|Value)
#  name: kafka_$1_$2_$3_$6
#  labels:
#    "$4": "$5"